[build]
command = "npm ci || echo 'no build'"
publish = "public"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

# (Opcional) que la raíz responda con una función health
# [[redirects]]
# from = "/"
# to = "/.netlify/functions/health"
# status = 200
